import { writeFile } from "node:fs/promises";
import path from "node:path";
import { isUpworkMode } from "../src/constants/upwork";
import {
	getMarketingSitemapEntries,
	PORTFOLIO_PRERENDER_PATHS,
	SITE_URL,
	type SitemapEntry,
} from "../src/seo";

const publicDir = path.resolve(import.meta.dirname, "..", "public");

function escapeXml(value: string): string {
	return value
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;")
		.replace(/'/g, "&apos;");
}

function formatSitemap(entries: SitemapEntry[]): string {
	const urls = entries
		.map(
			(entry) => `  <url>
    <loc>${escapeXml(entry.loc)}</loc>
    <lastmod>${escapeXml(entry.lastmod)}</lastmod>
  </url>`,
		)
		.join("\n");

	return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

const robotsTxt = isUpworkMode
	? `User-agent: *
Disallow: /
`
	: `User-agent: *
Allow: /

Sitemap: ${SITE_URL}/sitemap.xml
`;

const RETIRED_PATH_REDIRECTS: ReadonlyArray<{ from: string; to: string }> = [
	{ from: "/dual-brand-consumer-platform", to: "/projects" },
];

function formatRedirects(): string {
	const trailingSlashRules = PORTFOLIO_PRERENDER_PATHS.filter(
		(routePath) => routePath !== "/",
	).map((routePath) => `${routePath}/ ${routePath} 301`);

	const retiredPathRules = RETIRED_PATH_REDIRECTS.flatMap(({ from, to }) => [
		`${from} ${to} 301`,
		`${from}/ ${to} 301`,
	]);

	return [
		"# Generated by node-scripts/generate-sitemaps.ts — do not edit by hand.",
		"# Trailing-slash redirects.",
		...trailingSlashRules,
		"# Removed pages.",
		...retiredPathRules,
		"",
	].join("\n");
}

await writeFile(
	path.join(publicDir, "sitemap.xml"),
	formatSitemap(getMarketingSitemapEntries()),
	"utf8",
);
await writeFile(path.join(publicDir, "robots.txt"), robotsTxt, "utf8");
await writeFile(path.join(publicDir, "_redirects"), formatRedirects(), "utf8");
